version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "6301:6301"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${DATA_PATH}/nginx/html:/usr/share/nginx/html
      - ${DATA_PATH}/nginx/logs:/var/log/nginx
    restart: "always"

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ${DATA_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
    restart: "always"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ${DATA_PATH}/reids:/data
    restart: "always"
    command: redis-server /etc/redis/redis.conf
