version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "6301:6301"
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/sites:/usr/share/nginx/html
      - ${DATA_PATH}/nginx/logs:/var/log/nginx

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: "always"
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - $PWD/mysql/my.cnf:/etc/mysql/my.cnf
      - ${DATA_PATH}/mysql:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    restart: "always"
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis.conf:/etc/redis/redis.conf
      - ${DATA_PATH}/redis:/data

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: "always"
    depends_on:
      - mysql
    ports:
      - "7001:80"
    env_file:
      .env
    volumes:
      - ${DATA_PATH}/wordpress:/var/www/html
