version: "3.8"

services:
  ### ============================================
  ### Web Servers
  ### ============================================
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "6301:6301"
      - "6302:6302"
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/sites:/usr/share/nginx/html
      - $PWD/nginx/ssl:/etc/nginx/ssl
      - ${DATA_PATH}/nginx/logs:/var/log/nginx

  certbot:
      build:
        context: ./certbot
      volumes_from:
        - applications
      volumes:
        - ./data/certbot/certs/:/var/certs
      environment:
        - CN="fake.domain.com"
        - EMAIL="fake.email@gmail.com"

  ### ============================================
  ### Databases
  ### ============================================
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - $PWD/mysql/my.cnf:/etc/mysql/my.cnf
      - ${DATA_PATH}/mysql:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis.conf:/etc/redis/redis.conf
      - ${DATA_PATH}/redis:/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/mongo/data:/data/db
      - ${DATA_PATH}/mongo/config:/data/configdb

  ### ============================================
  ### Applications
  ### ============================================
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "7001:80"
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/wordpress:/var/www/html

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7002:80"
    env_file:
      - .env

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "7003:8080"
